version: 1.0.{build}
branches:
  only:
    - master
    - ci
image: Visual Studio 2022
configuration: Release
platform: x64
clone_folder: c:\projects\uacme
build:
  project: Source/uacme.sln
  verbosity: normal

artifacts:
  - path: "**/*.exe"
    name: exes

  - path: "**/*.dll"
    name: dlls

  - path: Build/
    name: build dir
    type: zip
